services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-container
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-container:/var/lib/postgresql/data
volumes:
  postgres-container:
